#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-eco-source
Version  : 1.1.0.rc.1
Release  : 5
URL      : https://rubygems.org/downloads/eco-source-1.1.0.rc.1.gem
Source0  : https://rubygems.org/downloads/eco-source-1.1.0.rc.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n eco-source-1.1.0.rc.1
gem spec %{SOURCE0} -l --ruby > rubygem-eco-source.gemspec

%build
gem build rubygem-eco-source.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
eco-source-1.1.0.rc.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/eco-source-1.1.0.rc.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/eco-source-1.1.0.rc.1/lib/eco/eco.js
/usr/lib64/ruby/gems/2.3.0/gems/eco-source-1.1.0.rc.1/lib/eco/source.rb
/usr/lib64/ruby/gems/2.3.0/specifications/eco-source-1.1.0.rc.1.gemspec
